//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH
    {
        public string MaSo { get; set; }
        public string HoTen { get; set; }
        public string MaLop { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
    }
}
